// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZkuZi3SDloNKFD6XBQj6zkSNRA5QBbUw',
    appId: '1:38276053882:web:b314a6c210b33454e834c3',
    messagingSenderId: '38276053882',
    projectId: 'vitallinkv2',
    authDomain: 'vitallinkv2.firebaseapp.com',
    storageBucket: 'vitallinkv2.firebasestorage.app',
    measurementId: 'G-W5H3GYYJ7Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpVyDRgHmfqnJk5oBiXHzur3siNa8E744',
    appId: '1:38276053882:android:a358f4ba94b8fc96e834c3',
    messagingSenderId: '38276053882',
    projectId: 'vitallinkv2',
    storageBucket: 'vitallinkv2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBabV5aRaBPUO8iba7ShWQBrE76chLpfls',
    appId: '1:38276053882:ios:8ae87540c6be8777e834c3',
    messagingSenderId: '38276053882',
    projectId: 'vitallinkv2',
    storageBucket: 'vitallinkv2.firebasestorage.app',
    iosBundleId: 'com.groupone.vitallink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBabV5aRaBPUO8iba7ShWQBrE76chLpfls',
    appId: '1:38276053882:ios:3e4356ed4b463f05e834c3',
    messagingSenderId: '38276053882',
    projectId: 'vitallinkv2',
    storageBucket: 'vitallinkv2.firebasestorage.app',
    iosBundleId: 'com.example.vitallinkv2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZkuZi3SDloNKFD6XBQj6zkSNRA5QBbUw',
    appId: '1:38276053882:web:227ec7e0f3b6c8e5e834c3',
    messagingSenderId: '38276053882',
    projectId: 'vitallinkv2',
    authDomain: 'vitallinkv2.firebaseapp.com',
    storageBucket: 'vitallinkv2.firebasestorage.app',
    measurementId: 'G-3C1LNJ5W1C',
  );
}
